# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 11:22
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_auto_20170122_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxentry',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/Users/krcnyc/Projects/CCUTTERS/EB/imagetrac_docker/uploads'), upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='inboxentry',
            name='attachment10',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/Users/krcnyc/Projects/CCUTTERS/EB/imagetrac_docker/uploads'), upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='inboxentry',
            name='attachment2',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/Users/krcnyc/Projects/CCUTTERS/EB/imagetrac_docker/uploads'), upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='inboxentry',
            name='attachment3',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/Users/krcnyc/Projects/CCUTTERS/EB/imagetrac_docker/uploads'), upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='inboxentry',
            name='attachment4',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/Users/krcnyc/Projects/CCUTTERS/EB/imagetrac_docker/uploads'), upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='inboxentry',
            name='attachment5',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/Users/krcnyc/Projects/CCUTTERS/EB/imagetrac_docker/uploads'), upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='inboxentry',
            name='attachment6',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/Users/krcnyc/Projects/CCUTTERS/EB/imagetrac_docker/uploads'), upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='inboxentry',
            name='attachment7',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/Users/krcnyc/Projects/CCUTTERS/EB/imagetrac_docker/uploads'), upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='inboxentry',
            name='attachment8',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/Users/krcnyc/Projects/CCUTTERS/EB/imagetrac_docker/uploads'), upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='inboxentry',
            name='attachment9',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/Users/krcnyc/Projects/CCUTTERS/EB/imagetrac_docker/uploads'), upload_to='attachments/'),
        ),
    ]
